language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greet

node_js:
  - "v9.11.2"

services:
  - postgresql

before_script:
  - psql -c 'create database  greet;' -U postgres
  - psql -U postgres -d greet -a -f tables.sql

after_success: npm run coverage

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2